trigger:
- none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - components/docker4gis-registry/**

stages:
- stage: pr_stage
  displayName: Pull Request stage
  pool:
    name: Azure Pipelines
  jobs:
  - job: pr_job
    displayName: Pull Request job
    steps:
    - checkout: self
      fetchDepth: 1
      sparseCheckoutDirectories: components/docker4gis-registry
      displayName: Git checkout
    
    - bash: |
        npx --yes docker4gis@latest build
      displayName: docker4gis build
      workingDirectory: components/docker4gis-registry
