#!/bin/bash
set -e

if [ "$1" = 'postgis' ]; then
	export PGUSER="${POSTGRES_USER}"
	postfix.sh
	/tmp/conf.sh
	/tmp/onstart.sh &
	exec docker-entrypoint.sh postgres -c 'config_file=/etc/postgresql/postgresql.conf'
fi

exec "$@"
