#!/bin/bash
set -e

export PGUSER="${POSTGRES_USER}"

if [ "$1" = 'postgis' ]; then
	/tmp/conf.sh
	/tmp/onstart.sh &
	exec docker-entrypoint.sh postgres -c 'config_file=/etc/postgresql/postgresql.conf'
fi

exec "$@"
