#!/bin/bash

if [ "$1" = 'postfix' ]; then
	DEFAULT='$myhostname localhost.$mydomain localhost'
	postconf -e "mydestination=$DEFAULT $DESTINATION"
	cp /etc/postfix/transport.template /etc/postfix/transport
	sed -i -e "s/{{DESTINATION}}/${DESTINATION}/g" /etc/postfix/transport
	postmap /etc/postfix/transport
	rsyslogd
	postfix start
	exec tail -f /var/log/maillog
fi

exec "$@"
