#!/bin/bash
set -e

action=$1

[ "$action" = s ] && action='set'
[ "$action" = c ] && action='components'

if [ "$action" = set ] || [ "$action" = components ]; then
	shift
	exec /devops/"$action".sh "$@"
fi

# This allows you to, in rare cases, run a container with a different command.
exec "$@"
