#!/bin/bash
set -e

action=$1

[ "$action" = s ] && action='set'
[ "$action" = c ] && action='components'

if [ "$action" = -p ] || [ "$action" = --project ] || [[ $action =~ ^--project= ]]; then
	action='project'
fi

case "$action" in
set | components | project)
	if [ "$action" = project ]; then
		action=components
	else
		shift
	fi
	exec /devops/"$action".sh "$@"
	;;
*)
	# This allows you to, in rare cases, run a container with a different command.
	exec "$@"
	;;
esac
