trigger:
# NOTE: "npm-package" -> "master" after merge
  branches:
    include:
    - npm-package
  paths:
    include:
    - packages/docker4gis-cli/**

pr:
- none


steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 1
  sparseCheckoutDirectories: packages/docker4gis-cli
  displayName: 'git checkout'

# Login to the Docker Hub, so that we can push the image we'll build.
- bash: |
    echo '$(DOCKER_PASSWORD)' | docker login -u=docker4gis --password-stdin docker.io
  displayName: 'docker login'
  workingDirectory: packages/docker4gis-cli

# Test the authorisation for NPM, so that we know we can publish the package
# we're updating. Using the environment variable placeholder in .npmrc; see
# https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file.
- bash: |
    npm whoami
  displayName: 'npm login'
  workingDirectory: packages/docker4gis-cli
  env:
    NPM_TOKEN: '$(NPM_TOKEN)'

# Configure git with the pipeline's details.
- bash: |
    git config --global user.email 'pipeline@azure.com'
    git config --global user.name 'Azure Pipeline'
  displayName: 'git config'
  workingDirectory: packages/docker4gis-cli

# Prepare the git repo to accept commits.
# NOTE: "npm-package" -> "master" (2x) after merge
- bash: |
    git checkout -b npm-package
    git push --set-upstream origin npm-package
  displayName: 'git undo detached state'
  workingDirectory: packages/docker4gis-cli


# Run shared workflow for release mode: bump version, build/push package image,
# publish npm package, then push git commit and tags.
- bash: |
    PUBLISH_MODE=release ./base/publish_docker4gis_version.sh
  displayName: 'publish release'
  workingDirectory: packages/docker4gis-cli
  env:
    NPM_TOKEN: '$(NPM_TOKEN)'
