trigger:
- none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - packages/docker4gis-cli/**

steps:
# Shallow checkout is sufficient for BV and avoids persisting credentials.
- checkout: self
  fetchDepth: 1
  sparseCheckoutDirectories: packages/docker4gis-cli
  displayName: Git checkout

# Build the package image.
- bash: |
    ./build.sh
  displayName: 'build package image'
  workingDirectory: packages/docker4gis-cli/base/package
