#!/bin/sh
set -e

if [ "$1" = 'proxy' ]; then
	shift 1
	/conf.sh "$@"
	cp -u /tmp/conf/certificates/* /certificates
	exec /proxy
fi

# This allows you to, in rare cases, run a container with a different command.
exec "$@"
