#!/bin/bash

HERE=$(dirname "$0")
set -a
# shellcheck source=/dev/null
. "$HERE"/.env
set +a

case "$1" in
build)
	# Build new image for component, tagging it as "latest".
	# Examples:
	# ./ex build proxy
	# ./ex build postgis
	# ./ex build geoserver
	# ./ex build app
	;;
run) ;;
br)
	# Build, and then run
	# Examples:
	# ./ex br proxy
	# ./ex br postgis
	# ./ex br geoserver
	# ./ex br app
	;;
push)
	# Push a component's image to the registry.
	# If a tag is provided, the "latest" image is tagged and pushed as such.
	# The "latest" image is pushed in all cases.
	# Examples:
	# ./ex push api
	# ./ex push api 137
	;;
test)
	# Run a specific component's unit tests,
	# or the application's integration tests.
	# Examples:
	# ./ex test proxy
	# ./ex test app
	# ./ex test
	;;
stop)
	# Stop running containers.
	# Examples:
	# ./ex stop
	;;
geoserver)
	# Write the GeoServer container's config to your working directory.
	# Examples:
	# ./ex geoserver
	# ./ex geoserver app_name
	;;
esac

DIR="$(mktemp -d)"
docker container run --rm -v "$DIR":/host docker4gis/docker4gis:"$DOCKER_VERSION" dump

DOCKER_BASE="$DIR"/base
export DOCKER_BASE

"$DOCKER_BASE/main.sh" "$0" "$@"

rm -rf "$DIR"
