#!/bin/bash
set -e

# edit here
export DOCKER_USER='template'

# Fork the merkatorgis/docker4gis repo and set the environment variable
# to the docker4gis/base directory
export DOCKER_BASE="${DOCKER_BASE}"
echo "DOCKER_BASE: ${DOCKER_BASE}"

action="${1:-start}"
shift 1

export PROXY_HOST='localhost.merkator.com'
export PROXY_PORT="${PROXY_PORT:-7443}"
export APP="${APP:-http://${DOCKER_USER}-app:5000/}"
export API="${API:-http://${DOCKER_USER}-api:8080/}"

# export DOCKER_REGISTRY="${DOCKER_REGISTRY:-docker.merkator.com/}"
export NETWORK_NAME="${DOCKER_USER}-net"
export DOCKER_BINDS_DIR="${DOCKER_BASE}/../binds"

export PROXY_CONTAINER="${DOCKER_USER}-px"
export POSTGIS_CONTAINER="${DOCKER_USER}-pg"
export GEOSERVER_CONTAINER="${DOCKER_USER}-gs"
export MAPFISH_CONTAINER="${DOCKER_USER}-mf"
export POSTFIX_CONTAINER="${DOCKER_USER}-pf"
export CRON_CONTAINER="${DOCKER_USER}-cr"
export PHP_CONTAINER="${DOCKER_USER}-pp"
export API_CONTAINER="${DOCKER_USER}-api"
export APP_CONTAINER="${DOCKER_USER}-app"

export MSYS_NO_PATHCONV=1

if [ "${action}" == 'start' ]; then
	"${DOCKER_BASE}/start.sh" "${GEOSERVER_CONTAINER}"
	"${DOCKER_BASE}/start.sh" "${MAPFISH_CONTAINER}"
	"${DOCKER_BASE}/start.sh" "${CRON_CONTAINER}"
	"${DOCKER_BASE}/start.sh" "${POSTFIX_CONTAINER}"
	"${DOCKER_BASE}/start.sh" "${API_CONTAINER}"
	"${DOCKER_BASE}/start.sh" "${POSTGIS_CONTAINER}"
	"${DOCKER_BASE}/start.sh" "${APP_CONTAINER}"
	"${DOCKER_BASE}/start.sh" "${PROXY_CONTAINER}"
elif [ "${action}" == 'stop' ]; then
	"${DOCKER_BASE}/stop.sh" "${PROXY_CONTAINER}"
	"${DOCKER_BASE}/stop.sh" "${APP_CONTAINER}"
	"${DOCKER_BASE}/stop.sh" "${POSTGIS_CONTAINER}"
	"${DOCKER_BASE}/stop.sh" "${API_CONTAINER}"
	"${DOCKER_BASE}/stop.sh" "${POSTFIX_CONTAINER}"
	"${DOCKER_BASE}/stop.sh" "${CRON_CONTAINER}"
	"${DOCKER_BASE}/stop.sh" "${MAPFISH_CONTAINER}"
	"${DOCKER_BASE}/stop.sh" "${GEOSERVER_CONTAINER}"
elif [ "${action}" == 'build' ]; then
	# Examples:
	# ./ex build app
	# ./ex build app 627
	# APP_TAG=627 ./ex build run 38
	# ./ex build api; ./ex br app
	export PROXY_TAG="${PROXY_TAG}"
	export POSTFIX_TAG="${POSTFIX_TAG}"
	export POSTGIS_TAG="${POSTGIS_TAG}"
	export GEOSERVER_TAG="${GEOSERVER_TAG}"
	export MAPFISH_TAG="${MAPFISH_TAG}"
	export CRON_TAG="${CRON_TAG}"
	export API_TAG="${API_TAG}"
	export APP_TAG="${APP_TAG}"
	"${DOCKER_BASE}/build.sh" "$0" "$@"
elif [ "${action}" == 'run' ]; then
	# Examples:
	# ./ex run
	# ./ex run 38
	"${DOCKER_BASE}/run.sh" "$0" "$@"
elif [ "${action}" == 'br' ]; then
	# Examples:
	# ./ex br app
	# ./ex br postgis
	"$0" build "${1}"
	"$0" run
elif [ "${action}" == 'latest' ]; then
	"${DOCKER_BASE}/latest.sh" postfix "${POSTFIX_CONTAINER}"
	"${DOCKER_BASE}/latest.sh" geoserver "${GEOSERVER_CONTAINER}"
	"${DOCKER_BASE}/latest.sh" mapfish "${MAPFISH_CONTAINER}"
	"${DOCKER_BASE}/latest.sh" cron "${CRON_CONTAINER}"
	"${DOCKER_BASE}/latest.sh" api "${API_CONTAINER}"
	"${DOCKER_BASE}/latest.sh" run no_container
	"${DOCKER_BASE}/latest.sh" postgis "${POSTGIS_CONTAINER}"
	"${DOCKER_BASE}/latest.sh" app "${APP_CONTAINER}"
	"${DOCKER_BASE}/latest.sh" proxy "${PROXY_CONTAINER}"

	"$0" run
else
	echo "Unknown action: ${action}"
fi
