#!/bin/sh
set -e

if [ "$1" = 'geoserver' ]; then
	from=$DOCKER_CONTAINER:$GEOSERVER_DATA_DIR
	to=./conf/geoserver_data
	echo "
		echo 'About to replace $to with $from'
		read -rn 1 -p 'Press any key to continue (or Ctrl-C to cancel) ... '
		echo
		rm -rf '$to'
		docker container cp '$from' '$to'
	"
fi
