#!/bin/bash

image=$DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPO

if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ]; then
    echo "Usage: eval \"\$(docker container run --rm $image:<TAG> /.docker4gis/run <TAG>)\""
    exit 1
fi

DOCKER_TAG=$1
DOCKER_IMAGE=$image:$DOCKER_TAG

echo "
# Start the container using the docker4gis framework embedded in the image,
# extracted using a dummy container to copy it from.
(
    export DOCKER_REGISTRY=$DOCKER_REGISTRY
    export DOCKER_USER=$DOCKER_USER
    temp=\$(mktemp -d) &&
        dummy=\$(docker container create '$DOCKER_IMAGE') &&
        docker container cp \"\$dummy\":/.docker4gis \"\$temp\" &&
        docker container rm \"\$dummy\" >/dev/null &&
        cd \"\$temp\"/.docker4gis &&
        docker4gis/run.sh '$DOCKER_REPO' '$DOCKER_TAG'
    result=\$?
    rm -rf \"\$temp\"
    exit \$result
)"
