FROM docker4gis/postgis

# To create a mail box login@destination:
# RUN addmailbox.sh {login} 'Full Name'
# eg RUN addmailbox.sh noreply 'Merkator DXF-service'
RUN addmailbox.sh noreply 'Merkator DXF-service'
