#!/bin/sh
set -e

if [ "$1" = 'swagger' ]; then
	shift 1

	# Here you can configure stuff, if needed, before starting the original
	# ENTRYPOINT/CMD (which you can find by `inspect`ing the image you're
	# extending FROM).

	exec /docker-entrypoint.sh nginx -g 'daemon off;' "$@"
fi

# This allows you to, in rare cases, run a container with a different command.
exec "$@"
