FROM docker4gis/postfix:latest

ENV DESTINATION=example.com
# And/or set POSTFIX_DESTINATION at run time

# To create a mail box login@destination:
# RUN addmailbox.sh {login} 'Full Name'

# To process incoming mail by a script:
# RUN api.sh {login} /tmp/conf/script_name.sh param1 param2
