#!/bin/bash

if [ "$1" = 'postfix' ]; then
	postconf -e "myorigin=${DESTINATION}"

	# shellcheck disable=SC2016
	default_destination='$myhostname localhost.$mydomain localhost'
	postconf -e "mydestination=${default_destination} ${DESTINATION}"

	postconf -e "$(postconf export_environment) DESTINATION=${DESTINATION}"

	# see api.sh
	cp /usr/local/bin/runner.sh "/usr/local/bin/$DOCKER_USER"

	touch /onstart
	# shellcheck source=/dev/null
	. /onstart

	postconf -e "maillog_file = /dev/stdout"
	exec postfix start-fg
fi

exec "$@"
