#!/bin/bash
set -e

if [ "$1" = 'tomcat' ]
then
	if [ -d /tmp/conf ]
	then
		cp -r /tmp/conf/webapps/* \
			"${CATALINA_HOME}/webapps"

		cp -r /tmp/conf/CATALINA_HOME/* \
			"${CATALINA_HOME}"

		host_ip=$(ip route show default | awk '/default/ {print $3}')
		echo "host.ip=${host_ip//\./\\\.}" >> \
			"${CATALINA_HOME}/conf/catalina.properties"

		/tmp/conf/conf.sh
		rm -rf /tmp/conf
	fi
	JAVA_OPTS="${JAVA_OPTS} ${EXTRA_JAVA_OPTS}" exec catalina.sh run
fi

exec "$@"
