
-- login should be on your exposed schema, eg:

-- create or replace function dxf.fn_login
--     ( in_email text
--     , in_password text
--     )
-- returns auth.jwt_token
-- language plpgsql
-- as $$
-- declare
--   -- check email and password; throws invalid_password exception
--   c_role name := auth.fn_user_role(in_email, in_password);
--   result auth.jwt_token;
-- begin
--     select sign
--         ( row_to_json(r)
--         , current_setting('app.jwt_secret')
--         ) as token
--     from (
--         select c_role as role
--         -- , fn_login.in_email as email
--         -- , extract(epoch from now())::integer + 60*60 as exp
--         , extract(epoch from now())::integer as iat
--     ) r
--     into result;
--     return result;
-- end;
-- $$;
