
-- login should be on your exposed schema, eg:

-- create or replace function dxf.fn_login
--     ( in_email text
--     , in_password text
--     )
-- returns auth.jwt_token
-- language sql
-- as $$
-- -- Fast logins are insecure
-- select pg_sleep(3);
-- -- auth.fn_user_role checks email and password, returns role,
-- -- and throws invalid_password exception
-- select auth.fn_jwt_token
--     ( (select auth.fn_user_role
--         ( in_email
--         , in_password
--         ))
--     , 60 * 60 -- one hour
--     );
-- $$;
