trigger:
  branches:
    include:
    - npm-package
  paths:
    include:
    - components/docker4gis-serve/**

pr:
- none


pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 1
  sparseCheckoutDirectories: components/docker4gis-serve
  displayName: 'git checkout'

- script: |
    echo '$(DOCKER_PASSWORD)' | docker login -u=docker4gis --password-stdin docker.io
  displayName: 'docker login'

- script: |
    git config --global user.email 'pipeline@azure.com'
    git config --global user.name 'Azure Pipeline'
  displayName: 'git config'

- script: |
    git checkout -b npm-package
    git push --set-upstream origin npm-package
  displayName: 'git undo detached state'

- script: |
    npx --yes docker4gis@latest push
  displayName: 'docker4gis push'
  workingDirectory: components/docker4gis-serve
