FROM docker4gis/osm:latest

# See https://github.com/Overv/openstreetmap-tile-server

ENV DOWNLOAD_PBF https://download.geofabrik.de/europe/belgium-latest.osm.pbf
ENV DOWNLOAD_POLY https://download.geofabrik.de/europe/belgium.poly
