#!/bin/sh
set -e

if [ "$1" = 'postgis-ddl' ]; then
    shift

    # Here you can configure stuff, if needed, before starting the original
    # ENTRYPOINT/CMD (which you can find by `inspect`ing the image you're
    # extending FROM).

    exec /onstart.sh "$@"
fi

# This allows you to, in rare cases, run a container with a different command.
exec "$@"
