#!/bin/bash
set -e
set -x

if [ "$1" = 'tomcat' ]; then
	shift 1

	# Here you can configure stuff, if needed, before starting the original
	# ENTRYPOINT/CMD (which you can find by `inspect`ing the image you're
	# extending FROM).

	# conf just once, on container create
	if [ -d /tmp/conf ]; then
		cp -r /tmp/conf/webapps/* \
			"${CATALINA_HOME}/webapps"

		cp -r /tmp/conf/CATALINA_HOME/* \
			"${CATALINA_HOME}"

		find /tmp/conf -name "conf.sh" -exec /tmp/conf/subconf.sh {} \;

		rm -rf /tmp/conf
	fi

	# run Tomcat with configured options
	JAVA_OPTS="-Xms${XMS} -Xmx${XMX} ${JAVA_OPTS} ${EXTRA_JAVA_OPTS}" exec catalina.sh run
fi

# This allows you to, in rare cases, run a container with a different command.
exec "$@"
