#!/bin/bash
set -e

if [ "$1" = 'tomcat' ]
then

	# conf just once, on container create
	if [ -d /tmp/conf ]
	then
		cp -r /tmp/conf/webapps/* \
			"${CATALINA_HOME}/webapps"

		cp -r /tmp/conf/CATALINA_HOME/* \
			"${CATALINA_HOME}"

		host_ip=$(ip route show default | awk '/default/ {print $3}')
		echo "host.ip=${host_ip//\./\\\.}" >> \
			"${CATALINA_HOME}/conf/catalina.properties"

		find /tmp/conf -name "conf.sh" -exec /tmp/conf/subconf.sh {} \;

		rm -rf /tmp/conf
	fi

	# run Tomcat with configured options
	JAVA_OPTS="-Xms${XMS} -Xmx${XMX} ${JAVA_OPTS} ${EXTRA_JAVA_OPTS}" exec catalina.sh run
fi

exec "$@"
