#!/bin/bash
set -e

if [ "$1" = 'geoserver' ]; then
	if [ -d /tmp/conf ]; then
		/tmp/conf/conf.sh
		rm -rf /tmp/conf
	fi
	cp -r /dynamic/ "${GEOSERVER_DATA_DIR}/workspaces/"
	find "$GEOSERVER_DATA_DIR" -name 'datastore.xml' -exec /datastore.sh {} \;
	cp "/certificates/$GEOSERVER_HOST.key" /usr/local/tomcat/conf/host.key
	cp "/certificates/$GEOSERVER_HOST.crt" /usr/local/tomcat/conf/host.crt
	exec catalina.sh run
fi

exec "$@"
