#!/bin/sh
set -e

if [ "$1" = 'postgrest' ]; then
	shift 1

	# Here you can configure stuff, if needed, before starting the original
	# ENTRYPOINT/CMD (which you can find by `inspect`ing the image you're
	# extending FROM).

	# Only startup and db connection recovery messages are logged
	# PGRST_LOG_LEVEL=crit
	# All the "crit" level events plus server errors (status 5xx) are logged
	# PGRST_LOG_LEVEL=error
	# All the "error" level events plus request errors (status 4xx) are logged
	# PGRST_LOG_LEVEL=warn
	# All the "warn" level events plus all requests (every status code) are logged
	# PGRST_LOG_LEVEL=info
	# Because currently there’s no buffering for logging, the levels with minimal
	# logging(crit/error) will increase throughput.
	default_pgrst_log_level=error
	[ "$DOCKER_ENV" = DEVELOPMENT ] && default_pgrst_log_level=info
	PGRST_LOG_LEVEL=${PGRST_LOG_LEVEL:-$default_pgrst_log_level}
	export PGRST_LOG_LEVEL

	exec /usr/bin/postgrest "$@"
fi

# This allows you to, in rare cases, run a container with a different command.
exec "$@"
