#!/bin/bash
set -e

if [ "$1" = 'tomcat' ]
then
	if [ -d /tmp/conf ]
	then
		cp /tmp/conf/war/*.war "${CATALINA_HOME}/webapps"

		/tmp/conf/conf.sh
		rm -rf /tmp/conf
	fi
	exec catalina.sh run
fi

exec "$@"
