#!/bin/bash
set -e

if [ "$1" = 'qgis' ]; then

	# Render the files directory writable from Apache.
	dir=/fileport/files/qgis
	mkdir -p "$dir"
	chown -R www-data "$dir"

	# run the QGIS Server
	exec start-server
fi

exec "$@"
