trigger:
- none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - components/docker4gis-proxy/**

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 1
  sparseCheckoutDirectories: components/docker4gis-proxy
  displayName: 'git checkout'

- script: |
    npx --yes docker4gis@latest build
  displayName: 'docker4gis build'
  workingDirectory: components/docker4gis-proxy
