#!/bin/sh
set -e

if [ "$1" = 'serve' ]; then
	shift 1

	# Here you can configure stuff, if needed, before starting the original
	# ENTRYPOINT/CMD (which you can find by `inspect`ing the image you're
	# extending FROM).

	if [ "$DYNAMIC" ]; then
		wwwroot=/fileport/root
		[ "$SUB" ] && wwwroot=$wwwroot/$SUB
		mkdir -p "$wwwroot"
		[ -d /wwwroot ] || ln -s "$wwwroot" /wwwroot
	fi
	[ -f /wwwroot/serve.json ] || cp /serve.json /wwwroot
	if [ "$SINGLE" ]; then
		exec serve --listen 80 --single /wwwroot
	else
		exec serve --listen 80 /wwwroot
	fi
fi

# This allows you to, in rare cases, run a container with a different command.
exec "$@"
