#!/bin/bash
# set -x

EXCLUDE_SCHEMA=$EXCLUDE_SCHEMA
DOCKER_TAG=$DOCKER_TAG

cores=$(nproc --all)
jobs=$cores

schema=
database=$PGDATABASE

for _ in '-n' '-d'; do
    case "$1" in
    -n)
        schema=$2 && shift 2
        ;;
    -d)
        database=$2 && shift 2
        ;;
    esac
done

SNAPSHOT_DIR=${SNAPSHOT_DIR:-/snapshot}
dir=${1:-/fileport/$database}
[ "$dir" = snapshot ] && dir=$SNAPSHOT_DIR

[ "$schema" ] && dir=$dir/$schema
mkdir -p "$dir" || exit

roles=$dir/roles
backup=$dir/backup
log=$dir/log
lst=$backup.lst
docker_tag=$dir/docker_tag

tag() {
    tag=$(date -I'seconds')
    for f in "$roles" "$backup" "$log" "$lst" "$docker_tag"; do
        [ -e "$f" ] &&
            mv "$f" "$f.$tag"
    done
    return 0
}

sql() {
    local dbname=$database
    [ "$1" = "-d" ] && dbname=$2 && shift 2
    run() {
        # use --no-align and --tuples-only to return a proper, unformatted
        # value that can be used in conditional statements
        psql -U "$POSTGRES_USER" -d "$dbname" --no-align --tuples-only "$@"
    }
    local input=$1 && shift 1
    if [ "$input" ]; then
        if [ -f "$input" ]; then
            # read from given file
            run -f "$input" "$@"
        else
            # execute given sql command
            run -c "$input" "$@"
        fi
    else
        # read from stdin
        run
    fi
}

# create a new dump, while online
dump() {
    # save app.jwt_secret and any other settings passed as an argument, to get
    # set again as part of the restore
    local settings="
        -- if we're upgrading, we're in default read-only mode
        start transaction read write;

        drop function if exists __restore_settings;
        create function __restore_settings
            ( database_name text
            )
        returns void language plpgsql as \$body\$ begin
    "
    local value
    for setting in app.jwt_secret "$@"; do
        value=$(sql "select current_setting('$setting', true)")
        settings+="execute format
            ( \$format\$
                alter database %s set $setting to '$value'
              \$format\$
            , database_name
            );"
    done
    settings+="
        -- clean up after ourselves
        drop function __restore_settings;
        end \$body\$;
        commit;
    "
    time {
        sql "$settings" &&
            # tag any existing dump files, so that we won't overwrite them
            tag &&
            # save roles (they're not included in pg_dump's backup file)
            pg_dumpall -U "$POSTGRES_USER" --roles-only >"$roles" &&
            # backup database
            # https://postgis.net/docs/manual-dev/postgis_administration.html#hard_upgrade
            pg_dump \
                --username="$POSTGRES_USER" \
                --dbname="$database" \
                --exclude-schema="$EXCLUDE_SCHEMA" \
                --format=custom \
                --blobs \
                --verbose \
                --file="$backup" 2>&1 | tee "$log" &&
            echo "$DOCKER_TAG" >"$docker_tag" &&
            # we don't need this in the database anymore; it just needed to be
            # included in the dump
            sql "
                start transaction read write;
                drop function if exists __restore_settings;
                commit;
            " &&
            echo "Dump created: '$backup'"
    }
}

analyze() {
    # "it is wise to run ANALYZE after restoring from a dump file"
    # https://www.postgresql.org/docs/13/app-pgdump.html
    time {
        echo "Waiting for ANALYZE to complete..."
        sql "
            SET maintenance_work_mem TO '512MB';
            analyze;
        "
    }
    echo
}

restore() {

    do_restore() {
        # first restore the roles (which are not included in the backup file)
        sql "$roles" || return

        # prevent "schema already exists" errors
        sql "drop schema if exists tiger_data cascade"
        sql "drop schema if exists tiger cascade"

        # restore from the backup file

        local postgis_restore_pl
        postgis_restore_pl=$(find / -name postgis_restore.pl 2>/dev/null)
        if [ -x "$postgis_restore_pl" ]; then
            # Use postgis_restore_pl if it exists, see
            # https://postgis.net/docs/manual-dev/postgis_administration.html#hard_upgrade
            echo "Restoring using '$postgis_restore_pl'..."
            "$postgis_restore_pl" "$backup" | sql 2>&1 | tee "$log"
        else
            echo "Restoring using pg_restore..."
            pg_restore \
                --username="$POSTGRES_USER" \
                --dbname="$database" \
                --verbose \
                --jobs="$jobs" \
                "$backup" 2>&1 | tee "$log"
        fi
        # restore database settings
        sql "select __restore_settings('$database')"
        # tag the current dump files as done
        tag
        echo "Restored: '$backup.$tag'"
    }

    # If the database does not yet contain a schema named $DOCKER_USER, and a
    # database dump is present, restore the dump.
    if [ -z "$(sql "
        select true
        from information_schema.schemata
        where schema_name = '$DOCKER_USER'
    ")" ] && [ -f "$roles" ] && [ -f "$backup" ]; then
        echo "LOG:  Restoring dump from '$backup'..."
        time do_restore && analyze

        # Loop over any subdirectories of $SNAPSHOT_DIR to restore the
        # respective "excluded schemas".
        while IFS= read -r -d '' snapshot_subdirectory; do
            snapshot_schema=$(basename "$snapshot_subdirectory")
            /usr/local/bin/restore_schema -n "$snapshot_schema" "$SNAPSHOT_DIR"
        done < <(find "$SNAPSHOT_DIR" -mindepth 1 -maxdepth 1 -type d -print0)

        # In case we're restoring a snapshot (providing the initial DDL), run
        # the post-snapshot script, if it exists.
        post_snapshot_script="$dir"/post_snapshot.sh
        if [ "$dir" = "$SNAPSHOT_DIR" ] && [ -x "$post_snapshot_script" ]; then
            echo "LOG:  Running post-snapshot script..."
            (cd "$dir" &&
                "$post_snapshot_script")
            echo
        fi

    fi
}

schema() {
    # Ensure a schema name is specified.
    if [ -z "$schema" ]; then
        echo "Must specify schema, e.g. $action -n <schema-name>"
        exit 22
    fi
}

dump_schema() {
    time {
        schema &&
            # tag any existing dump files, so that we won't overwrite them
            tag &&
            # only the directory format supports dumping with parallel jobs
            pg_dump \
                --username="$POSTGRES_USER" \
                --dbname="$database" \
                --schema="$schema" \
                --format=directory \
                --blobs \
                --verbose \
                --jobs="$jobs" \
                --file="$backup" 2>&1 | tee "$log" &&
            echo "Dump created: '$backup'" &&
            chmod +rx "$backup" &&
            echo "$DOCKER_TAG" >"$backup/__docker_tag" &&
            if version=$(sql "select $schema.__version()" -At 2>/dev/null); then
                echo "$version" >"$backup/__version"
            fi
    }
}

restore_schema() {
    time {
        schema &&
            sql "create schema $schema" &&
            pg_restore \
                --username="$POSTGRES_USER" \
                --dbname="$database" \
                --schema="$schema" \
                --verbose \
                --jobs="$jobs" \
                "$backup" 2>&1 | tee "$log" &&
            sql "
                grant usage on schema $schema to public;
                grant select on all tables in schema $schema to public;
            " &&
            # tag the current dump files as done
            tag &&
            echo "Restored: '$backup.$tag'"
    } && analyze
}

# render the database read-only, before creating a new dump - restore the dump
# in a new, empty database to get it writable again
upgrade() {
    # Create a temporary database to connect to when terminating all connections
    # to the database to dump.
    local upgrade_database=__u__p__g__r__a__d__e__
    sql "drop database if exists $upgrade_database" &&
        sql "create database $upgrade_database" &&
        # Connect to NOT the database to dump.
        sql -d "$upgrade_database" "
            -- temporarily disallow new connections
            -- https://www.postgresql.org/docs/13/sql-alterdatabase.html
            alter database $database allow_connections false;

            -- make future connections read-only
            -- https://www.postgresql.org/docs/13/runtime-config-client.html
            alter database $database set default_transaction_read_only to on;

            -- terminate any (presumably writable) connections
            -- https://www.postgresql.org/docs/13/functions-admin.html
            -- https://www.postgresql.org/docs/13/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW
            select pg_terminate_backend(pid) from pg_stat_activity where datname = '$database';

            -- reallow new (read-only) connections
            alter database $database allow_connections true;
        " &&
        dump "$@" &&
        {
            echo >&2
            echo "NOTICE: since an 'upgrade' dump was created, database $database is now read-only..." >&2
            echo "  See https://github.com/merkatorgis/docker4gis/blob/master/docs/postgis.md#upgrade..." >&2
        }
}

flag() {
    if [ "$?" = 0 ]; then
        flag=DONE
    else
        flag=FAILED
    fi
    [ "$1" = start ] && {
        flag=BUSY
        if busy=$(ls "$dir"/BUSY.*.flag 2>/dev/null); then
            echo "Exiting since another dump/restore process is still busy:"
            echo "$busy"
            exit 1
        fi
    }
    ext=$action.flag
    # Remove any old flag.
    rm -f "$dir"/*."$ext"
    # Write new flag.
    touch "$dir/$flag.$ext"
    # Succeed or fail.
    [ "$flag" = DONE ]
}

# dump | restore | upgrade | dump_schema | restore_schema (see Dockerfile)
action=$(basename "$0")

flag start
$action "$@"
flag
