#!/bin/sh
set -e

if [ "$1" = 'postgis' ]; then
	shift 1

	# Here you can configure stuff, if needed, before starting the original
	# ENTRYPOINT/CMD (which you can find by `inspect`ing the image you're
	# extending FROM).

	export PGUSER="$POSTGRES_USER"

	# start the mail sending deamon
	runner.sh postfix.sh

	# configure postgresql for startup
	/conf.sh

	# kick off configuration scripts after the database has started
	/onstart.sh 2>&1 | tee --append /onstart.log &

	# run the database server
	exec docker-entrypoint.sh postgres -c "config_file=$CONFIG_FILE"
fi

# This allows you to, in rare cases, run a container with a different command.
exec "$@"
